### PR TITLE
Add new cross references to MESH

### PR DESCRIPTION
**Pull request by bgyori**
This PR adds 974 new cross references from DOID entries to MeSH. These mappings are useful for data/knowledge integration across content using DOIDs and MeSH IDs. To generate these new mappings, we used [Gilda](https://github.com/indralab/gilda) to find matches between DOID and MeSH specifically for DOIDs that previously didn't have MeSH mappings. We then used the [Biomappings](https://github.com/biopragmatics/biomappings) web-based curation interface to review and curate each predicted mapping. The mappings that were reviewed and deemed correct were then added to doid-edit.owl.

Note that this contribution is similar to ones already accepted/merged in MONDO (https://github.com/monarch-initiative/mondo/pull/4930), Uberon (https://github.com/obophenotype/uberon/pull/2432), and CL (https://github.com/obophenotype/cell-ontology/pull/1561).

To make it easier to review cross-references added in this PR, I created a spreadsheet providing human-readable names and additional information [here](https://github.com/bgyori/HumanDiseaseOntology/blob/a0fc2d877f190dd749cc968a76f63a76e03cf31b/doid_mesh_review.tsv).

Please let me know if this looks good or if any changes are needed!

### CODE REVIEW

**Comment by allenbaron** [comment]
Thank you for providing these mappings to the Disease Ontology. We would like to review them in a tabular format and to load them with ROBOT. Would you be willing to open this as an issue instead?

Thanks!

**Comment by cthoyt** [comment]
@allenbaron can you describe the format we'd have to put these xrefs in to do this?

**Comment by allenbaron** [comment]
Thanks. The request to open an issue was mostly for attribution and tracking purposes because we don't plan to merge this PR directly, but I can get the ORCID IDs directly from the spreadsheet and opening an issue seems redundant.

The linked spreadsheet is all we need. We downloaded it and have started review in the spreadsheet, so we can keep notes and also add MeSH synonyms. We will put those xrefs that are correct and the synonyms into a ROBOT template and load it into the DO. This ROBOT workflow is easier for us than editing this PR, especially since we're adding synonyms too.

In the past when reviewing MeSH xrefs, we have noticed that there is often not a 1:1 match when there are disease subtypes. A quick initial review of the new MeSH xrefs identified two DO-MeSH pairs that we would not add as exact for this reason. Is there a way for us to provide feedback on the xrefs we find that are incorrect?

**Comment by bgyori** [comment]
Thanks @allenbaron. I'm curious which cases showed differences between the DO-MeSH definitions. I think it's fairly common that there are two disease terms that are meant to be equivalent but DO and MeSH chose to curate a different set of subterms, or one of them contains subterms, the other doesn't, etc. But this is not always a sign of the two parent terms actually being meaningfully different. As example might be a term like "cancer" in two ontologies, where the subterms might be substantially different due to distinct curation practices, yet the two "cancer" terms are actually meant to represent the same disease. In any case, some specific examples would be useful to discuss!

**Pull request closed without merging**
