### PR TITLE
Update and rename DO_LICENSE.txt to LICENSE

### PR DESCRIPTION
**Pull request by cthoyt**

### CODE REVIEW

**Comment by allenbaron** [comment]
@lschriml this is the version of the CC0 license available on [Github](https://choosealicense.com/licenses/cc0-1.0/) which is formatted better for reading along with code and on Github. It also has a portion of the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/legalcode) that our current license was missing (the CC disclaimer at the top). 

Github states that software might include an optional [boilerplate](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F) at the top of the license but I think this is fine as is.

**Comment by lschriml** [comment]
I have updated the file as outlined.
Closing the request.

**Comment by cthoyt** [comment]
Just a note on GitHub etiquette - it seems that you've made an alternate solution to this issue, committed it directly to the main branch of the repository, and dismissed this pull request without merge. This has the consequence that the contribution will not be reflected in the commit history.

I've put some time and thought into helping improve this repository and having this happen does not feel very great.

If you're in this situation again, please consider making your edits directly on the branch associated with the pull request. You can do this directly in the GitHub interface for the pull request.

**Comment by lschriml** [comment]
Apologies Charlie. 
I did not mean to do this incorrectly. 
I created a DO ticket, https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/1011
to recognize the contribution. 

Cheers,
Lynn

**Pull request closed without merging**
